name: Array Test
on:
  workflow_dispatch: # can be triggered manually

jobs:
  draw:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # So the reference to the parent commit is available when amending
          fetch-depth: 2
      - name: Draw keymaps
        id: draw
        run: |
          set -o xtrace
          mkdir -p "images"
          declare -a DRAWINGS
          for keymap_file in config/*.keymap; do
              keyboard=$(basename -s .keymap "$keymap_file")
              echo "INFO: drawing for $keyboard"
              echo "$keyboard" >images.$keyboard.yaml
              echo "$keyboard" >images.$keyboard.svg
              if [[ ${FIRST} -ne 1 ]]; then
                OUTPUTS="${OUTPUTS},"
              fi
              OUTPUTS="${OUTPUTS}\"images/$keyboard.yaml\",\"images/$keyboard.svg\""
              DRAWINGS+="images/$keyboard.yaml"
              DRAWINGS+="images/$keyboard.svg"
          done
          ls -la images config
          echo "OUTPUTS=[${OUTPUTS}]" >> $GITHUB_OUTPUT
          echo "DRAWINGS=${DRAWINGS[@]} >> $GITHUB_OUTPUT

      - name: Artifact1 upload
        id: artifact-upload-step1
        uses: actions/upload-artifact@v4
        with:
          name: 'drawings-JSON'
          path: |
            ${{ join(fromJSON(steps.draw.outputs.OUTPUTS), '
            ') }}
      - name: Artifact2 upload
        id: artifact-upload-step2
        uses: actions/upload-artifact@v4
        with:
          name: 'drawings-ARRAY'
          path: |
            ${{ join(steps.draw.outputs.DRAWINGS, '\n') }}
           
