name: Array Test
on:
  workflow_dispatch: # can be triggered manually

jobs:
  draw:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # So the reference to the parent commit is available when amending
          fetch-depth: 2
      - name: Draw keymaps
        id: draw
        run: |
          IFS=','
          declare -a DRAWINGS
          mkdir -p "images"
          for keymap_file in config/*.keymap; do
              keyboard=$(basename -s .keymap "$keymap_file")
              echo "INFO: drawing for $keyboard"
              echo "$keyboard" >images/$keyboard.yaml
              echo "$keyboard" >images/$keyboard.svg
              DRAWINGS+=(\"images/$keyboard.yaml\" \"images/$keyboard.svg\")
          done
          echo "DRAWINGS=[${DRAWINGS[*]}]" >> $GITHUB_OUTPUT
          
      - name: Artifact upload
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: 'drawings'
          path: |
            ${{ join(fromJSON(steps.draw.outputs.DRAWINGS), '
            ') }}
           
